### ISSUE TITLE
error on require

### ISSUE THREAD

**Issue by ogaida** [kuroda/ansible_module#1]
Dear Mr. Kuroda,

I would like to use your module for building some ansible-modules in ruby. But if i require your module i got this error. What can i do?

```
irb(main):001:0> require 'ansible_module'
/var/lib/gems/2.5.0/gems/activesupport-4.1.16/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/var/lib/gems/2.5.0/gems/activesupport-4.1.16/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
Traceback (most recent call last):
        4482: from /usr/bin/irb:11:in `<main>'
        4481: from /usr/lib/ruby/2.5.0/irb.rb:383:in `start'
        4480: from /usr/lib/ruby/2.5.0/irb.rb:427:in `run'
        4479: from /usr/lib/ruby/2.5.0/irb.rb:427:in `catch'
        4478: from /usr/lib/ruby/2.5.0/irb.rb:428:in `block in run'
        4477: from /usr/lib/ruby/2.5.0/irb.rb:487:in `eval_input'
        4476: from /usr/lib/ruby/2.5.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
        4475: from /usr/lib/ruby/2.5.0/irb/ruby-lex.rb:231:in `catch'
         ... 4470 levels...
           4: from /var/lib/gems/2.5.0/gems/activesupport-4.1.16/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
           3: from /var/lib/gems/2.5.0/gems/activesupport-4.1.16/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
           2: from /var/lib/gems/2.5.0/gems/activesupport-4.1.16/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
           1: from /var/lib/gems/2.5.0/gems/activesupport-4.1.16/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
/var/lib/gems/2.5.0/gems/activesupport-4.1.16/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)
```

Kind regards
Oliver

**Comment by kuroda** [comment]
Your error messages are similar to those which are reported on this issue:

https://github.com/rails/rails/issues/27670

I'm not sure but it seems that this is a compatibility issue of Ruby and Rails.

You use Ruby 2.5.0 (rather new) and Rails 4.1.16 (very old).

The constants Fixnum and Bignum have been deprecated on Ruby 2.4.

Please try to downgrade your ruby to 2.3.

**Comment by ogaida** [comment]
thank you very much for the quick response. Downgrading is not an option for me, but you gave me the right direction. I have changed the Gemfile.lock and the gemspec from 

```
"activemodel", "~> 4.1.5" 
```

to 

```
"activesupport", ">= 4.1.5"
```

the same to activemodel. And build a new gem. Here are my installed gems. I suppose the gem uses the newest one:

```
gem list -l active

*** LOCAL GEMS ***

activejob (6.0.2.1, 4.2.10)
activemodel (6.0.2.1, 5.2.1, 4.2.10)
activerecord (6.0.2.1, 5.2.1, 4.2.10)
activeresource (4.1.0)
activestorage (6.0.2.1)
activesupport (6.0.2.1, 6.0.0, 5.2.1, 4.2.10)
```

**Comment by kuroda** [comment]
Thanks.
